/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DataLocationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "changeMemory"
      | "changeStorage"
      | "readCalldata"
      | "stored"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "changeMemory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "readCalldata",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "stored", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "changeMemory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readCalldata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stored", data: BytesLike): Result;
}

export interface DataLocation extends BaseContract {
  connect(runner?: ContractRunner | null): DataLocation;
  waitForDeployment(): Promise<this>;

  interface: DataLocationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  changeMemory: TypedContractMethod<[_temp: string], [string], "view">;

  changeStorage: TypedContractMethod<[], [void], "nonpayable">;

  readCalldata: TypedContractMethod<[_msg: string], [string], "view">;

  stored: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "changeMemory"
  ): TypedContractMethod<[_temp: string], [string], "view">;
  getFunction(
    nameOrSignature: "changeStorage"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "readCalldata"
  ): TypedContractMethod<[_msg: string], [string], "view">;
  getFunction(
    nameOrSignature: "stored"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
